server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "87fb9cfd75c281321060ca283c9ab4372061ab010d643d447b2740aa6f79b836"